---
provisioner:
  name: chef_zero

platforms:
  - name: CentOS_6
    driver:
      name: ec2
      require_chef_omnibus: true
      transport.username: centos
      transport.ssh_key: C:\Users\Jonny\.ssh\id_rsa
      aws_ssh_key_id: id_rsa
      region: <%= ENV['AWS_DEFAULT_REGION'] %>
      availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>a
      subnet_id: subnet-069a5e70
      instance_type: t1.micro
      image_id: ami-b6bdde86
      security_group_ids: ['sg-d8517dbf']
      retryable_tries: 120
      associate_public_ip: true

suites:
  - name: default
    run_list:
      - recipe[project_maduro::default]
    attributes:
