---
provisioner:
  name: chef_zero

driver:
  name: ec2
  security_group_ids: ['sg-30317156']
  region: <%= ENV['AWS_REGION'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']%>
  availability_zone: <%= ENV['AWS_DEFAULT_REGION'] %>
  subnet_id: subnet-069a5e70
  image_id: ami-b6bdde86
  associate_public_ip: true
  retryable_tries: 30
  instance_type: t1.micro
  block_device_mappings:
  - device_name: /dev/sda
    ebs:
      volume_size: 20
      delete_on_termination: true
  require_chef_omnibus: true

platforms:
  - name: CentOS_67

transport:
  name: ssh
  ssh_key: <%= ENV['AWS_SSH_KEY'] %>
  username: root

suites:
  - name: default
    run_list:
      - recipe[project_maduro::default]
    attributes:
