name 'project_maduro'
maintainer 'Jonathan Thompson'
maintainer_email 'nfernal13@outlook.com'
license 'all_rights'
description 'Installs/Configures project_maduro'
long_description 'Installs/Configures project_maduro'
version '0.1.0'

depends 'yum-epel'
depends 'iptables'
depends 'selinux'
